import React from 'react';
import { Barcode, Check, PackagePlus, Plus, Shirt, Tags, Trash2, X } from 'lucide-react';
import { AppLayout } from '../components/AppLayout.jsx';
import { brandService, inventoryService } from '../services/api.js';
const blank={nombre:'',barcode:'',marca:'',precio:'',stock:1};
export function IngresoMercaderiaPage(props){
 const[form,setForm]=React.useState(blank),[batch,setBatch]=React.useState([]),[brands,setBrands]=React.useState([]),[newBrand,setNewBrand]=React.useState(''),[brandModal,setBrandModal]=React.useState(false),[msg,setMsg]=React.useState('');
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const loadBrands=React.useCallback(()=>brandService.list().then(setBrands).catch(()=>setMsg('No pudimos cargar las marcas.')),[]);
 React.useEffect(()=>{loadBrands()},[loadBrands]);
 function add(){if(!form.nombre||!form.barcode||!form.marca||!form.precio){setMsg('Completa nombre, código, marca y precio.');return}setBatch(b=>[...b,form]);setForm(blank);setMsg('')}
 async function createBrand(e){e.preventDefault();try{const brand=await brandService.create(newBrand);setBrands(b=>[...b,brand].sort((a,z)=>a.nombre.localeCompare(z.nombre)));set('marca',brand.nombre);setNewBrand('');setBrandModal(false);setMsg('Marca creada correctamente.')}catch(err){setMsg(err.response?.data?.detail||'No fue posible crear la marca.');setBrandModal(false)}}
 async function save(){try{for(const item of batch)await inventoryService.create({...item,tipo:null,precio:Number(item.precio),stock:Number(item.stock)});setBatch([]);setMsg('Mercadería ingresada correctamente.')}catch(err){setMsg(err.response?.data?.detail||'No fue posible ingresar la mercadería.')}}
 return <AppLayout {...props} active="ingreso-mercaderia" title="Ingreso de mercadería" eyebrow="Recepción de productos"><div className="entry-grid"><section className="data-panel form-panel"><div className="form-heading"><span><PackagePlus/></span><div><h2>Nueva prenda</h2><p>Completa la información del producto que ingresa.</p></div></div><div className="form-grid"><label className="wide">Nombre de la prenda<input value={form.nombre} onChange={e=>set('nombre',e.target.value)} placeholder="Ej: Blusa lino manga larga"/></label><label>Código de barra<div className="input-icon"><Barcode/><input value={form.barcode} onChange={e=>set('barcode',e.target.value)} placeholder="Escanear o escribir"/></div></label><label>Marca<div className="brand-select-row"><select value={form.marca} onChange={e=>set('marca',e.target.value)}><option value="">Seleccionar marca</option>{brands.map(b=><option value={b.nombre} key={b.id}>{b.nombre}</option>)}</select><button type="button" onClick={()=>setBrandModal(true)} title="Crear nueva marca"><Plus/></button></div></label><label>Precio de venta<input type="number" min="0" value={form.precio} onChange={e=>set('precio',e.target.value)} placeholder="$ 0"/></label><label>Stock inicial<input type="number" min="0" value={form.stock} onChange={e=>set('stock',e.target.value)}/></label></div><button className="secondary-button add-batch" onClick={add}><Plus/> Agregar al ingreso</button></section><aside className="batch-panel"><div className="batch-head"><div><h2>Resumen del ingreso</h2><p>Prendas por registrar</p></div><span>{batch.length}</span></div>{batch.length?<div className="batch-list">{batch.map((x,i)=><div key={i}><span><Shirt/></span><p><strong>{x.nombre}</strong><small>{x.stock} un. · {x.marca}</small></p><button onClick={()=>setBatch(b=>b.filter((_,n)=>n!==i))}><Trash2/></button></div>)}</div>:<div className="empty-state compact"><Tags/><strong>Aún no hay prendas</strong><span>Agrega productos para revisar el ingreso.</span></div>}<button className="primary-button full" disabled={!batch.length} onClick={save}><Check/> Confirmar ingreso</button>{msg&&<p className="feedback center">{msg}</p>}</aside></div>
 {brandModal&&<div className="modal-backdrop" onMouseDown={()=>setBrandModal(false)}><form className="brand-modal" onSubmit={createBrand} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span><Tags/></span><div><h2>Nueva marca</h2><p>Se guardará para futuros ingresos.</p></div></div><button type="button" onClick={()=>setBrandModal(false)}><X/></button></div><label>Nombre de la marca<input autoFocus value={newBrand} onChange={e=>setNewBrand(e.target.value)} maxLength="100" placeholder="Ej: Girasol Collection" required/></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setBrandModal(false)}>Cancelar</button><button className="primary-button">Crear marca</button></div></form></div>}
 </AppLayout>
}
