import React from 'react';
import { AlertTriangle, Boxes, PackageCheck, Search, Tags } from 'lucide-react';
import { AppLayout } from '../components/AppLayout.jsx';
import { brandService, inventoryService } from '../services/api.js';
const money = v => new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 }).format(Number(v || 0));
export function InventarioPage(props) {
    const [search, setSearch] = React.useState(''), [brand, setBrand] = React.useState(''), [brands, setBrands] = React.useState([]), [rows, setRows] = React.useState([]), [loading, setLoading] = React.useState(true), [error, setError] = React.useState('');
    const [summary, setSummary] = React.useState({ prendas_registradas: 0, unidades_disponibles: 0, marcas: 0, stock_bajo: 0, umbral_stock_bajo: 5 });
    React.useEffect(() => { Promise.all([inventoryService.summary(), brandService.list()]).then(([stats, list]) => { setSummary(stats); setBrands(list) }).catch(() => setError('No pudimos cargar el resumen del inventario.')) }, []);
    React.useEffect(() => { const t = setTimeout(() => { setLoading(true); inventoryService.list(search, brand).then(r => { setRows(r); setError('') }).catch(() => setError('No pudimos conectar con el inventario.')).finally(() => setLoading(false)) }, 250); return () => clearTimeout(t) }, [search, brand]);
    return <AppLayout {...props} active="inventario" title="Inventario" eyebrow="Control de existencias">
        <section className="metric-grid"><Metric icon={<Boxes />} tone="yellow" label="Prendas registradas" value={summary.prendas_registradas} sub="productos diferentes" /><Metric icon={<PackageCheck />} tone="green" label="Unidades disponibles" value={summary.unidades_disponibles} sub="stock total" /><Metric icon={<Tags />} tone="blue" label="Marcas" value={summary.marcas} sub="registradas" /><Metric icon={<AlertTriangle />} tone="red" label="Stock bajo" value={summary.stock_bajo} sub={`hasta ${summary.umbral_stock_bajo} unidades`} /></section>
        <section className="data-panel"><div className="data-panel__top"><div><h2>Listado de prendas</h2><p>Consulta stock, precio y marca de cada producto.</p></div></div><div className="toolbar"><label className="search-field"><Search size={19} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar por nombre o código de barra..." /></label><select value={brand} onChange={e => setBrand(e.target.value)}><option value="">Todas las marcas</option>{brands.map(b => <option value={b.nombre} key={b.id}>{b.nombre}</option>)}</select></div>
            {error ? <div className="empty-state"><AlertTriangle /><strong>{error}</strong><span>Comprueba que el servidor local esté iniciado.</span></div> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Prenda</th><th>Código</th><th>Marca</th><th>Precio</th><th>Stock</th><th>Estado</th></tr></thead><tbody>{loading ? <tr><td colSpan="6" className="table-message">Cargando inventario…</td></tr> : rows.length ? rows.map((r, i) => { const n = Number(r['Total Stock'] || 0); return <tr key={r.id ?? i}><td><div className="product-cell"><span>{String(r.Prenda || 'P')[0]}</span><strong>{r.Prenda || 'Sin nombre'}</strong></div></td><td className="mono">{r.barcode || '—'}</td><td><span className="category-pill">{r.Marca || 'Sin marca'}</span></td><td><strong>{money(r.Precio)}</strong></td><td>{n} un.</td><td><span className={`status-pill ${n === 0 ? 'out' : n <= 5 ? 'low' : 'ok'}`}>{n === 0 ? 'Agotado' : n <= 5 ? 'Stock bajo' : 'Disponible'}</span></td></tr> }) : <tr><td colSpan="6" className="table-message">No encontramos prendas con esos filtros.</td></tr>}</tbody></table></div>}<footer className="panel-footer">Mostrando <strong>{rows.length}</strong> prendas</footer></section>
    </AppLayout>
}
function Metric({ icon, tone, label, value, sub }) { return <article className="metric-card"><span className={`metric-card__icon ${tone}`}>{icon}</span><div><small>{label}</small><strong>{value}</strong><em>{sub}</em></div></article> }
